export const Tools = {
    DockerContainers: "fetch_docker_containers",
    CreateDockerContainer: "create_docker_container",
    StartDockerContainer: "start_docker_container",
    DeleteDockerContainer: "delete_docker_container",
    ContainerLogs: "fetch_container_logs",
    UpdateContainer: "update_container_resource_limits",
    DeleteUnwantedContainers: "delete_stopped_containers",
    GetImages: "fetch_docker_images",
    DeleteImageBuilderCache: "delete_image_build_cache",
    DeleteUnusedImages: "delete_unused_images",
    GetNetworks: "fetch_docker_networks",
    GetServices: "fetch_docker_services",
    ServiceLogs: "fetch_service_logs",
    InspectService: "inspect_service",
    UpdateService: "update_docker_service",
};
